/*
 * timers.c
 *
 *  Created on: Apr 26, 2025
 *      Author: Kwief
 */

#include "main.h"
#include "timer.h"
void clock_config(void)
{
	FLASH->ACR |= FLASH_ACR_LATENCY_0;
	RCC->CR |= RCC_CR_HSION;
	 while (!(RCC->CR & RCC_CR_HSIRDY));
	// RCC->CR |= RCC_CFGR_PLLSRC
	 RCC->APB1ENR |= RCC_APB1ENR_PWREN;
	 RCC->CFGR |= RCC_CFGR_HPRE_DIV1;
	 RCC->CFGR|= RCC_CFGR_PPRE1_DIV2;
	 //PPL SOURCE MUX
	// RCC->CFGR |= RCC_CFGR_PLLMUL9;
	 RCC->CFGR |= (0x7 << RCC_CFGR_PLLMUL_Pos);
	 RCC->CR |= RCC_CR_PLLON;
	 while (!(RCC->CR & RCC_CR_PLLRDY));
	 RCC->CFGR |= RCC_CFGR_SW_PLL;
	 while(!(RCC->CFGR & RCC_CFGR_SWS));
	 RCC -> AHBENR |= RCC_AHBENR_GPIOAEN;
	 RCC -> AHBENR |= RCC_AHBENR_GPIOBEN;
	 RCC -> AHBENR |= RCC_AHBENR_GPIOCEN;
}

void configure_y_TIMER15(void)
{
	 //PA6:D12 CH1

	RCC -> APB2ENR |= RCC_APB2ENR_TIM15EN;

	TIM15->PSC = 79999;
	TIM15->ARR = 1;
    TIM15->CR1 |= TIM_CR1_ARPE;
	GPIOB->MODER |= GPIO_MODER_MODER10_0;
	TIM15->CNT=0;
	TIM15->CCMR1 |= (TIM_CCMR1_OC1M_0 | TIM_CCMR1_OC1M_1); //outputcomare config
    TIM15->CCER |= TIM_CCER_CC1E;
	//interuptTIM3
	TIM15 -> DIER |= TIM_DIER_UIE;
	TIM15 -> DIER |= TIM_DIER_CC1IE;
	NVIC_SetPriority(TIM1_BRK_TIM15_IRQn, 2);
	NVIC_EnableIRQ(TIM1_BRK_TIM15_IRQn);

}
void configure_x_TIMER2(void)
{
	RCC -> APB1ENR |= RCC_APB1ENR_TIM2EN;
	TIM2->PSC = 79999;
	TIM2->ARR = 1;
    TIM2->CR1 |= TIM_CR1_ARPE;
	GPIOA->MODER |= GPIO_MODER_MODER0_0;
	TIM2->CNT=0;
	TIM2->CCMR1 |= (TIM_CCMR1_OC1M_0 | TIM_CCMR1_OC1M_1);
    TIM2->CCER |= TIM_CCER_CC1E;
	//interuptTIM3
	TIM2 -> DIER |= TIM_DIER_UIE;
	TIM2 -> DIER |= TIM_DIER_CC1IE;
	NVIC_SetPriority(TIM2_IRQn, 1);
	NVIC_EnableIRQ(TIM2_IRQn);
}


void configure_z_TIMER17(void)
{
	//PC7

	RCC -> APB2ENR |= RCC_APB2ENR_TIM17EN;
	TIM17->PSC = 719999;
	TIM17->ARR = 1;
    TIM17->CR1 |= TIM_CR1_ARPE;
	GPIOA->MODER |= GPIO_MODER_MODER7_0;
	TIM17->CNT=0;
	TIM17->CCMR1 |= (TIM_CCMR1_OC1M_0 | TIM_CCMR1_OC1M_1);
    TIM17->CCER |= TIM_CCER_CC1E;
	//interuptTIM3
	TIM17 -> DIER |= TIM_DIER_UIE;
	TIM17 -> DIER |= TIM_DIER_CC1IE;
	NVIC_SetPriority(TIM1_TRG_COM_TIM17_IRQn, 3);
	NVIC_EnableIRQ(  TIM1_TRG_COM_TIM17_IRQn );
//	TIM4->CR1|= TIM_CR1_CEN;
}


void pwmconfigration(void)
{
	TIM3 -> CCMR1 |= TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2;
	TIM3 -> CCMR1 |= TIM_CCMR1_OC1PE;
	TIM3 -> CCR1 = 900;
	 TIM3->CR1 |= TIM_CR1_ARPE;
	TIM3 -> CCER |= TIM_CCER_CC1E;
}
